name:                union-find-delete
version:             0.1.0.0
stability:           provisional
github:              "WorldSEnder/union-find-delete"
license:             GPL-3
author:              Martin Molzer <worldsbegin@gmx.de>
maintainer:          Martin Molzer <worldsbegin@gmx.de>
copyright:           "2021 Martin Molzer"
bug-reports:         https://github.com/WorldSEnder/union-find-delete/issues

extra-source-files:
- README.md

synopsis:            A union find implementation supporting a delete operation
category:            Algorithms, Data

description:         Please see the README on GitHub at <https://github.com/WorldSEnder/union-find-delete#readme>

dependencies:
- base >= 4.7 && < 5
- data-default-class >= 0.1.2
- containers >= 0.6.2 && < 0.7
- transformers >= 0.5.6 && < 0.6
- profunctors >= 5.5.2 && < 5.6
- mtl >= 2.2.2 && < 2.3
- lens >= 4.19

library:
  source-dirs: src

default-language:
- Haskell2010

default-extensions:
- BangPatterns
- ConstraintKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTSyntax
- KindSignatures
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TypeApplications

- TemplateHaskell
- TypeFamilies

tests:
  functionality-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - union-find-delete
    - HUnit >= 1.6.1 && < 2
    - tasty >= 1.2
    - tasty-hunit
    - data-default >= 0.7.1
